version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
    volumes :
     - /tmp/database:/var/lib/postgresql/data
    restart: always
